apiVersion: v1
kind: Service
metadata:
  name: geekprofile-email-service
  namespace: default
  labels:
    app: geekprofile-email
    tier: api
spec:
  selector:
    app: geekprofile-email
    tier: api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: pyport
